### PR TITLE
Nodes script with ca-certificate

### PR DESCRIPTION
**Pull request by dragononcrypto**
Wget command for linux.sh now includes ca-certificate (SSL) via github, required for Debian and Tails.

### CODE REVIEW

**Comment by dragononcrypto** [comment]
Updated to download deeponion.crt via openssl then execute wget command with --ca-certificate option.
Currently testing out new linux.sh script on different systems.
/certs directory with certificates probably no longer required.

**Comment by nezero** [comment]
Can you explain why the certificate is not trusted?

The certificate is trusted by all major operating systems, so it would seem strange that Debian does not trust it. It also puts the user at risk of a MITM attack. If you do things like, this it is no safer than using `--no-check-certificate` option with `wget`, it's effectively removing a lot of the security that signed TLS certificates provide.

**Comment by dragononcrypto** [comment]
The certificate is trusted, but when tested on debian by kk80586 there were wget problems downloading related to accessing the certificate. Cloudfare related as far as I understand. I don't see how downloading the certificate via openssl, then executing wget referencing the downloaded certificate, puts users at higher MITM risk though. It turns out the original script is working again on debian, so probably wasted a lot of time modifying it, instead of testing it.

**Comment by thohemp** [comment]
Thanks anyway :)

**Comment by nezero** [comment]
> The certificate is trusted, but when tested on debian by kk80586 there were wget problems downloading related to accessing the certificate. Cloudfare related as far as I understand. I don't see how downloading the certificate via openssl, then executing wget referencing the downloaded certificate, puts users at higher MITM risk though. It turns out the original script is working again on debian, so probably wasted a lot of time modifying it, instead of testing it.

Thanks. Drop me a message on the forums if you want to discuss this further. I'm happy to explain the risks even if the need for it no is longer required.

**Pull request closed without merging**
